# Generated by Django 5.2.1 on 2025-05-30 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã khách hàng')),
                ('name', models.CharField(max_length=100, verbose_name='Tên khách hàng')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Điện thoại')),
                ('total_sales', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Tổng bán')),
            ],
            options={
                'verbose_name': 'Khách hàng',
                'verbose_name_plural': 'Khách hàng',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên nhà cung cấp')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Số điện thoại')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Địa chỉ')),
            ],
            options={
                'verbose_name': 'Nhà cung cấp',
                'verbose_name_plural': 'Nhà cung cấp',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(max_length=20, unique=True, verbose_name='Mã đặt hàng')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tổng tiền')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Khách đã trả')),
                ('amount_due', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Khách cần trả')),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('processing', 'Đang xử lý'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.customer', verbose_name='Khách hàng')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Đơn hàng',
                'verbose_name_plural': 'Đơn hàng',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Tên nhóm hàng')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='inventory.productgroup', verbose_name='Nhóm hàng')),
            ],
            options={
                'verbose_name': 'Nhóm hàng',
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='Mã sản phẩm')),
                ('quantity', models.IntegerField()),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá bán')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Giá vốn')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Trọng lượng (gram)')),
                ('min_stock', models.IntegerField(default=0, verbose_name='Tồn kho tối thiểu')),
                ('max_stock', models.IntegerField(default=10, verbose_name='Tồn kho tối đa')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_stocked', models.DateField(blank=True, null=True, verbose_name='Ngày nhập kho')),
                ('date_sold', models.DateField(blank=True, null=True, verbose_name='Ngày xuất kho')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.productgroup', verbose_name='Nhóm hàng')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supplier', verbose_name='Nhà cung cấp')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Tên hiển thị')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Số điện thoại')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('role', models.CharField(choices=[('manager', 'Quản lý kho'), ('customer', 'Khách hàng')], default='manager', max_length=10, verbose_name='Vai trò')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
