# Generated by Django 5.2.1 on 2025-05-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Giá bán'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Mã sản phẩm'),
        ),
    ]
