# Generated by Django 5.2.1 on 2025-05-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventoryitem_selling_price_inventoryitem_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá bán'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='sku',
            field=models.CharField(max_length=50, unique=True, verbose_name='Mã sản phẩm'),
        ),
    ]
