# Generated by Django 5.2.1 on 2025-05-31 15:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_order_status_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payos_payment_link_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='PayOS Payment Link ID'),
        ),
        migrations.AddField(
            model_name='order',
            name='payos_payment_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Trạng thái thanh toán PayOS'),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Khách cần trả'),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Khách đã trả'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Chờ thanh toán'), ('paid', 'Đã thanh toán'), ('processing', 'Đang xử lý'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='pending_payment', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tổng tiền'),
        ),
    ]
