# Generated by Django 5.2.1 on 2025-05-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventoryitem_selling_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='date_sold',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày xuất kho'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='date_stocked',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày nhập kho'),
        ),
    ]
