# Generated by Django 5.2.1 on 2025-05-27 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventoryitem_date_sold_inventoryitem_date_stocked'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Tên nhóm hàng')),
            ],
            options={
                'verbose_name': 'Nhóm hàng',
                'verbose_name_plural': 'Nhóm hàng',
            },
        ),
    ]
