# Generated by Django 5.2.1 on 2025-05-27 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_productgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='product_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.productgroup', verbose_name='Nhóm hàng'),
        ),
    ]
