# Generated by Django 5.2.1 on 2025-05-27 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_inventoryitem_product_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgroup',
            options={'verbose_name': 'Nhóm hàng'},
        ),
        migrations.AddField(
            model_name='productgroup',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='inventory.productgroup', verbose_name='Nhóm hàng'),
        ),
    ]
