# Generated by Django 5.2.1 on 2025-05-27 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên nhà cung cấp')),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='Người liên hệ')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Địa chỉ')),
            ],
            options={
                'verbose_name': 'Nhà cung cấp',
                'verbose_name_plural': 'Nhà cung cấp',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Giá vốn'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='max_stock',
            field=models.IntegerField(default=10, verbose_name='Tồn kho tối đa'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='min_stock',
            field=models.IntegerField(default=0, verbose_name='Tồn kho tối thiểu'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Trọng lượng (gram)'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supplier', verbose_name='Nhà cung cấp'),
        ),
    ]
