# Generated by Django 5.2.1 on 2025-05-27 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_supplier_inventoryitem_cost_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='address',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='email',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='phone',
        ),
    ]
