# Generated by Django 5.2.1 on 2025-05-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã khách hàng')),
                ('name', models.CharField(max_length=100, verbose_name='Tên khách hàng')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Điện thoại')),
                ('total_sales', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Tổng bán')),
            ],
            options={
                'verbose_name': 'Khách hàng',
                'verbose_name_plural': 'Khách hàng',
                'ordering': ['code'],
            },
        ),
    ]
